In [19]:
import pandas as pd

In [20]:
excel_file = pd.read_excel('data/economic_data.xlsx')
excel_file

,date,title,country,indicator,comment,actual,previous,forecast,importance
0,23-01-2013 09:30:00 +0000,Inflation Rate YoY,CO,Inflation Rate,"In Colombia, the three main components of the ...",3.18,3.27,3.20,-1
1,23-01-2013 09:30:00 +0000,Inflation Rate MoM,CO,Inflation Rate Mom,Inflation Rate MoM measures month over month c...,0.30,0.12,0.32,-1
2,23-01-2013 09:30:00 +0000,Inflation Rate YoY,EG,Inflation Rate,"In Egypt, the headline Consumer Price Index (C...",3.10,4.80,NaN,-1
3,23-01-2013 09:30:00 +0000,Consumer Confidence,IE,Consumer Confidence,"In Ireland, the Consumer Sentiment Index surve...",75.30,77.20,NaN,-1
4,23-01-2013 09:30:00 +0000,Inflation Rate MoM,CO,Inflation Rate Mom,Inflation Rate MoM measures month over month c...,0.23,0.09,0.16,-1
...,...,...,...,...,...,...,...,...,...
175091,24-04-2023 06:00:00 +0100,PPI YoY,FI,Producer Prices Change,"In Finland, producer price index for manufactu...",3.80,9.20,NaN,-1
175092,24-04-2023 06:00:00 +0100,Inflation Rate YoY,SG,Inflation Rate,"In Singapore, the most important categories in...",5.50,6.30,5.60,-1
175093,24-04-2023 06:00:00 +0100,Import Prices YoY,FI,Import Prices YoY,"In Finland, Import Prices correspond to the ra...",0.70,7.60,NaN,-1
175094,24-04-2023 06:00:00 +0100,CPI,SG,Consumer Price Index CPI,"In Singapore, the Consumer Price Index or CPI ...",112.60,112.00,NaN,-1
175095,24-04-2023 06:00:00 +0100,Core Inflation Rate YoY,SG,Core Inflation Rate,"In Singapore, the core inflation rate tracks c...",5.00,5.50,5.10,-1

In [21]:
excel_file.country.value_counts().head()

country
US    23071
JP     7156
GB     6483
DE     5116
FR     4785
Name: count, dtype: int64

In [22]:
excel_file_filter = excel_file[excel_file['country'].isin(['US', 'JP', 'GB', 'DE', 'CA', 'EU', 'AU', 'CN', 'CH', 'NZ'])]
excel_file_filter

,date,title,country,indicator,comment,actual,previous,forecast,importance
26,23-01-2013 09:30:00 +0000,Total Vehicle Sales,US,Total Vehicle Sales,"In the United States, Total Vehicle Sales meas...",16.6,16.70,16.8,0
30,23-01-2013 09:30:00 +0000,Total Vehicle Sales,US,Total Vehicle Sales,"In the United States, Total Vehicle Sales meas...",16.7,17.55,17.2,0
39,15-03-2013 13:55:00 +0000,Reuters/Michigan Consumer Sentiment Index,US,Calendar,NaN,71.8,77.60,78.0,0
40,15-03-2013 13:15:00 +0000,Industrial Production MoM,US,Calendar,"In the United States, industrial production me...",0.7,-0.10,0.4,0
41,15-03-2013 13:15:00 +0000,Capacity Utilization,US,Calendar,Capacity utilization rate is used to measure t...,79.6,79.20,79.3,-1
...,...,...,...,...,...,...,...,...,...
175058,24-04-2023 13:30:00 +0100,New Housing Price Index YoY,CA,House Price Index YoY,NaN,0.2,1.40,NaN,0
175059,24-04-2023 13:30:00 +0100,New Housing Price Index MoM,CA,House Price Index MoM,"In Canada, New Housing Price Index (NHPI) meas...",0.0,-0.20,-0.5,0
175078,24-04-2023 09:00:00 +0100,Ifo Current Conditions,DE,Ifo Current Conditions,Assessment of the Business Situation.,95.0,95.40,96.0,-1
175080,24-04-2023 09:00:00 +0100,Ifo Expectations,DE,Ifo Expectations,Expectations With Regard to Business Developme...,92.2,91.00,91.5,-1
175081,24-04-2023 09:00:00 +0100,Ifo Business Climate,DE,Business Confidence,"In Germany, the IFO Business Climate Index mea...",93.6,93.20,94.0,1

In [23]:
excel_file_cp = excel_file.copy()
excel_file_cp['comment'] = excel_file_cp['comment'].fillna('')

In [24]:
switzerland_rows = excel_file_cp[excel_file_cp['comment'].str.contains('Switzerland', case=False)]
switzerland_rows

,date,title,country,indicator,comment,actual,previous,forecast,importance
111,14-03-2013 08:30:00 +0000,SNB Interest Rate Decision,CH,Interest Rate,"In Switzerland, interest rate decisions are ta...",0.00,0.00,0.0,0
195,12-03-2013 09:30:00 +0000,Balance of Trade,GB,Balance of Trade,The UK's trade balance has been in deficit sin...,-2.36,-2.81,-3.0,1
244,11-03-2013 08:15:00 +0000,Retail Sales MoM,CH,Retail Sales MoM,"In Switzerland, the Retail sales report provid...",-0.50,0.90,NaN,-1
245,11-03-2013 08:15:00 +0000,Retail Sales YoY,CH,Retail Sales YoY,"In Switzerland, the year-over-year change in R...",1.90,4.70,2.8,0
261,11-03-2013 07:00:00 +0000,Balance of Trade,DE,Balance of Trade,Germany runs regular trade surpluses since 195...,13.70,12.10,15.7,1
...,...,...,...,...,...,...,...,...,...
174745,28-04-2023 07:30:00 +0100,Retail Sales YoY,CH,Retail Sales YoY,"In Switzerland, the year-over-year change in R...",-1.90,-0.50,NaN,0
174746,28-04-2023 07:30:00 +0100,Retail Sales MoM,CH,Retail Sales MoM,"In Switzerland, the Retail sales report provid...",-0.10,0.50,NaN,-1
174831,27-04-2023 11:00:00 +0100,Imports,IL,Imports,Israel main imports are: machinery and equipme...,8048.20,7747.70,NaN,-1
174946,26-04-2023 09:00:00 +0100,Economic Sentiment Index,CH,Zew Economic Sentiment Index,"In Switzerland, the CS-CFA Society Economic Se...",-33.30,-41.30,NaN,-1
175036,25-04-2023 07:00:00 +0100,Balance of Trade,CH,Balance of Trade,Switzerland has been running consistent trade ...,3.10,2.40,NaN,0

In [25]:
newzealand_rows = excel_file_cp[excel_file_cp['comment'].str.contains('New Zealand', case=False)]
newzealand_rows

,date,title,country,indicator,comment,actual,previous,forecast,importance
133,13-03-2013 20:00:00 +0000,Interest Rate Decision,NZ,Interest Rate,"In New Zealand, interest rates decisions are t...",2.500,2.500,2.5,0
411,07-03-2013 00:30:00 +0000,Balance of Trade,AU,Balance of Trade,Australia has been recording consistent trade ...,-1.100,-0.400,0.7,1
903,03-04-2013 02:30:00 +0100,Balance of Trade,AU,Balance of Trade,Australia has been recording consistent trade ...,-178.000,-1215.000,-1000.0,1
1102,27-03-2013 21:45:00 +0000,Building Permits MoM,NZ,Calendar,"In New Zealand, Building Permits are measured ...",1.900,-0.400,NaN,-1
1151,27-03-2013 00:00:00 +0000,ANZ Business Confidence,NZ,Business Confidence,"In New Zealand, the business confidence index ...",34.600,39.400,NaN,-1
...,...,...,...,...,...,...,...,...,...
174793,27-04-2023 23:00:00 +0100,ANZ Roy Morgan Consumer Confidence,NZ,ANZ Roy Morgan Consumer Confidence Index,"In New Zealand, ANZ Roy Morgan Consumer Confid...",79.300,77.700,NaN,-1
174887,27-04-2023 02:00:00 +0100,ANZ Business Confidence,NZ,Business Confidence,"In New Zealand, the business confidence index ...",-43.800,-43.400,NaN,0
174976,25-04-2023 23:45:00 +0100,Balance of Trade,NZ,Balance of Trade,New Zealand is greatly dependent on internatio...,-1.273,-0.796,NaN,0
174977,25-04-2023 23:45:00 +0100,Exports,NZ,Exports,New Zealandâ€™s economy is greatly dependent on ...,6.510,5.060,NaN,-1
174978,25-04-2023 23:45:00 +0100,Imports,NZ,Imports,New Zealand imports mainly vehicles (13 percen...,7.780,5.860,NaN,-1

In [26]:
csv_file = excel_file_filter.to_csv('data/economic_data.csv', index=False)