# Boolean Indexing

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
pd.options.display.max_columns = 10

#### Old method

In [4]:
# data = pd.read_csv('../cookbook_data/owndata/economic_calendar_2.csv', index_col=1)
# data.drop('id', axis=1, inplace=True)

# time_format = '%d/%m/%Y'
# data.index = pd.to_datetime(data.index, format=time_format)

#### New method

In [7]:
data = pd.read_csv('../cookbook_data/owndata/economic_calendar_2.csv')
# data.drop('id', axis=1, inplace=True)
data.head()

,id,date,time,zone,currency,importance,event,actual,forecast,previous
0,750,01/02/2022,All Day,china,NaN,NaN,China - Spring Festival,NaN,NaN,NaN
1,750,01/02/2022,All Day,china,NaN,NaN,China - Spring Festival,NaN,NaN,NaN
2,445158,01/02/2022,00:40,united states,USD,medium,FOMC Member George Speaks,NaN,NaN,NaN
3,443182,01/02/2022,04:30,australia,AUD,medium,AIG Manufacturing Index (Dec),48.4,NaN,54.8
4,444835,01/02/2022,04:45,new zealand,NZD,medium,Trade Balance (YoY) (Dec),"-6,780M",NaN,"-6,230M"

In [8]:
sentiments = pd.read_csv('../cookbook_data/owndata/sentiments_df.csv')
sentiments.head()

   Symbol Action  Percentage   Volume  Positions
0  EURNZD  Short          94   885.40       3933
1  NZDCHF   Long          94   412.07       2210
2  AUDNZD  Short          90  2009.36       6147
3  NZDCAD   Long          89  1213.36       3964
4  GBPNZD  Short          89  1517.87       5873

In [14]:
sentiments.index = sentiments['Symbol'] + '_' + sentiments['Action']
sentiments.drop(['Symbol', 'Action'], axis=1, inplace=True)
sentiments = sentiments.sort_index()
sentiments.head()

              Percentage  Volume  Positions
AUDCAD_Long           61  732.84       3967
AUDCAD_Short          39  458.96       2919
AUDCHF_Long           67  416.51       2051
AUDCHF_Short          33  205.48       1127
AUDJPY_Long           43  229.65       1274

In [15]:
sentiments.sort_values(by=['Percentage'], ascending=False).head(6)

              Percentage   Volume  Positions
EURNZD_Short          94   885.40       3933
NZDCHF_Long           94   412.07       2210
AUDNZD_Short          90  2009.36       6147
GBPNZD_Short          89  1517.87       5873
NZDCAD_Long           89  1213.36       3964
EURJPY_Short          86  7174.50      15913

In [19]:
# sentiments.loc[['EURNZD_Long', 'NZDCHF_Short']]
sentiments.sort_values(by=['Percentage'], ascending=False).tail(6)

              Percentage   Volume  Positions
EURJPY_Long           14  1136.54       4039
NZDCAD_Short          11   145.04        848
GBPNZD_Long           11   178.42       1135
AUDNZD_Long           10   229.07       1170
NZDCHF_Short           6    28.62        430
EURNZD_Long            6    52.03        497